# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CamNangNguoiLaiXe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AlamofireObjectMapper'
  pod 'EZSwiftExtensions'
  pod 'EasyPeasy'
  pod 'AlamofireImage'
  pod 'Firebase/AdMob'
  pod 'Siren'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  # Pods for CamNangNguoiLaiXe

  target 'CamNangNguoiLaiXeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CamNangNguoiLaiXeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
